/**
 * backfill_corporate_responses.mjs
 *
 * Patches corporate profiles (v3-v7) that received Type 3 default responses
 * with their actual documented public positions where those exist.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));

const KNOWN_RESPONSES = {
  // ─── v3 ───────────────────────────────────────────────────────────────────
  'nestle': "Nestlé has publicly disputed characterizations of its baby formula marketing as systematically violating the WHO Code, stating it is committed to responsible marketing and has updated its policies multiple times. On water privatization, Nestlé has stated that access to water is a human right while maintaining that water as a commercial product is a different category — a position its former CEO Peter Brabeck-Letmathe made on record in a 2005 documentary, which Nestlé subsequently stated was misrepresented. Nestlé has acknowledged child labor concerns in its cocoa supply chain and published annual progress reports on remediation efforts while stating full elimination of child labor in complex agricultural supply chains requires systemic change beyond any single company.",
  'johnson-and-johnson': "Johnson & Johnson has disputed the characterization that it knowingly sold talc products containing asbestos, stating its talc has been tested thousands of times and found safe. In the opioid context, J&J reached a $5 billion settlement without admitting liability, stating it settled to avoid prolonged litigation while maintaining its marketing was appropriate. J&J has used the LTL Management subsidiary bankruptcy strategy — twice — which courts have rejected as bad faith; J&J has characterized this approach as a legitimate mechanism to ensure equitable distribution of settlement funds to plaintiffs.",
  'nestle': "Nestlé has publicly disputed characterizations of its baby formula marketing as systematically violating the WHO Code, stating it is committed to responsible marketing. On water privatization, Nestlé has stated that its former CEO's comments were taken out of context and that the company supports water as a human right. Nestlé has acknowledged child labor in its cocoa supply chain and published annual progress reports on remediation.",
  'pepsico': "PepsiCo has disputed allegations of deceptive health marketing, stating its portfolio transformation — reducing added sugars, sodium, and saturated fats — demonstrates genuine commitment to healthier products. PepsiCo has stated it complies with all applicable advertising standards and that its marketing to children follows self-regulatory guidelines. No formal public response to specific water extraction allegations in drought-affected areas has been documented beyond general sustainability commitments.",
  'procter-and-gamble': "Procter & Gamble has disputed greenwashing allegations, stating its sustainability commitments are genuine and audited. P&G has stated it complies with all applicable environmental disclosure standards. On PFAS in products, P&G has stated it is working to eliminate PFAS from its product portfolio where technically feasible. No formal public response to specific supply chain labor allegations has been documented beyond general supplier code of conduct statements.",
  'samsung': "Samsung Group has disputed characterizations of Lee Jae-yong's corruption conviction as reflecting systemic corporate governance failure, characterizing it as an isolated case involving a former administration's pressure. Lee Jae-yong received a presidential pardon in 2022 and was reinstated as Samsung Electronics chairman. Samsung has stated it has implemented enhanced compliance and governance reforms. On labor union suppression, Samsung Electronics formally recognized its first labor union in 2021 after decades of maintaining a union-free policy, acknowledging a change in its approach.",
  'tyson-foods': "Tyson Foods has disputed characterizations of its water pollution violations as systematic, stating it has invested billions in wastewater treatment and environmental compliance. Tyson has acknowledged worker safety issues during COVID-19 — including the internal executive betting pool on worker infections, which it characterized as 'reprehensible' and stated led to the firing of the involved managers. Tyson has stated it has implemented enhanced food safety and worker safety protocols. On immigration enforcement actions at its facilities, Tyson has stated it uses E-Verify and cannot be responsible for employees who provide fraudulent documents.",
  'walmart': "Walmart has disputed the characterization of its wage practices as systematically exploitative, stating it has raised its minimum starting wage and provides comprehensive benefits. On the $282 million FCPA Mexico bribery settlement, Walmart did not admit wrongdoing but stated it has implemented extensive global compliance reforms. Walmart has disputed environmental violation characterizations, stating it has made significant sustainability commitments including a pledge to reach zero emissions by 2040. On worker misclassification and wage theft settlements, Walmart has stated these resolved legacy issues and that current practices comply with applicable law.",
  'h-and-m': "H&M has disputed greenwashing allegations, stating its Conscious Collection and sustainability claims are based on genuine life cycle assessments and third-party verification. Following the Norwegian Consumer Authority finding that its sustainability claims were misleading, H&M stated it would improve transparency in its environmental communications. H&M has acknowledged supply chain labor concerns and published supplier lists while stating it requires suppliers to meet its sustainability standards. H&M has stated it is working to transition to a fully circular business model.",

  // ─── v4 ───────────────────────────────────────────────────────────────────
  'bosch': "Robert Bosch GmbH has acknowledged providing diesel engine management software used in the Volkswagen defeat device scandal, reaching a $327.5 million settlement with US regulators in 2017 without admitting wrongdoing. Bosch stated it relied on assurances from Volkswagen that the software would be used legally and that it was not aware of the defeat device application. No formal public response to specific labor or environmental allegations beyond the diesel settlement has been documented.",
  'dji': "DJI has formally disputed US government national security designations, stating its drones do not transmit data to the Chinese government and that its data security practices have been independently verified. DJI has stated it has implemented a local data mode that prevents any internet transmission and has invited independent security audits. DJI has disputed labor violation allegations in its Shenzhen manufacturing operations, stating it complies with all applicable Chinese labor law.",
  'haier': "Haier Group has not issued formal public responses to specific allegations regarding labor practices in its supply chain beyond general compliance statements. On its acquisition of GE Appliances, Haier has stated the transaction was commercially motivated and that GE Appliances operates independently. No formal public response to data security concerns about Chinese ownership of consumer appliance data has been documented beyond general privacy policy statements.",
  'lindt': "Lindt & Sprüngli has acknowledged child labor concerns in its West African cocoa supply chain and published annual sustainability reports documenting its remediation programs. Lindt has stated it is committed to eliminating child labor from its supply chain by 2025 and has implemented direct farmer engagement programs in Côte d'Ivoire and Ghana. Lindt has disputed characterizations of its cocoa sourcing as knowingly exploitative, stating it has invested significantly in sustainable cocoa programs.",
  'primark': "Primark has disputed characterizations of its fast fashion model as inherently exploitative, stating it has implemented robust supplier standards and audit programs. Following the Rana Plaza collapse — in which Primark-affiliated suppliers operated — Primark paid compensation to victims' families and stated it was the first retailer to do so voluntarily. Primark has stated it is committed to sustainable cotton sourcing and has joined the Better Cotton Initiative. On living wage allegations, Primark has stated it requires suppliers to pay at least the legal minimum wage and is working toward living wages.",
  'vale': "Vale has acknowledged the Brumadinho dam collapse as a catastrophic failure and agreed to a $7 billion compensation package for affected communities and environmental remediation — the largest settlement in Brazilian corporate history. Vale has stated it has implemented enhanced dam safety monitoring and has decommissioned upstream dams. On the earlier Mariana dam collapse (involving Samarco, a Vale joint venture), Vale stated Samarco bore operational responsibility while Vale contributed to the remediation fund. Vale has stated it has implemented the most rigorous dam safety standards in the industry following both disasters.",

  // ─── v5 ───────────────────────────────────────────────────────────────────
  'ab-inbev': "Anheuser-Busch InBev has disputed characterizations of its marketing practices as targeting underage drinkers or vulnerable populations, stating it complies with all applicable advertising standards and self-regulatory codes. AB InBev has stated it is committed to responsible drinking initiatives through its Global Smart Drinking Goals. On the $55 million SEC settlement for FCPA violations in India, AB InBev paid without admitting wrongdoing and stated it has implemented enhanced compliance programs. On its acquisition strategy's effect on craft beer diversity, AB InBev has stated acquired craft brands maintain their local character.",
  'airbnb': "Airbnb has acknowledged the racial discrimination documented in the Harvard Business School study and its own Project Lighthouse audit, stating it has implemented significant anti-discrimination measures including Project Lighthouse reforms, enhanced non-discrimination training, and open door policies for guests who experience discrimination. Airbnb has disputed the characterization that its housing market effects are primarily negative, stating it enables homeowners to earn supplemental income. Airbnb has stated it supports reasonable local regulation and works with municipalities on registration frameworks.",
  'cencora': "Cencora (formerly AmerisourceBergen) reached an $885 million settlement with the DOJ over opioid distribution without admitting wrongdoing, stating it has implemented enhanced suspicious order monitoring systems. Cencora has stated it was a distributor of legally manufactured pharmaceuticals and bore no responsibility for manufacturers' misleading marketing. No formal public response to specific allegations about its specialty drug pricing practices has been documented beyond general statements about the value of pharmaceutical distribution.",
  'deutsche-bank': "Deutsche Bank has acknowledged multiple regulatory settlements including the $7.2 billion mortgage securities settlement and the $630 million mirror trading fine, characterizing these as resolving legacy issues from a prior era of the bank. Deutsche Bank has stated it has implemented comprehensive cultural and compliance reforms under current leadership. On its relationship with Jeffrey Epstein, Deutsche Bank stated it should not have maintained the relationship and has implemented enhanced client due diligence. On its role in the 1MDB scandal, Deutsche Bank paid $186 million in regulatory settlements.",
  'dollar-tree': "Dollar Tree has disputed characterizations of its store conditions as systematically unsafe, stating it has invested in compliance programs following FDA enforcement actions at Family Dollar. Dollar Tree reached a $41.6 million settlement with the FDA over Family Dollar distribution center conditions and stated it has implemented enhanced food safety protocols. No formal public response to specific worker wage and classification allegations has been documented beyond general compliance statements.",
  'fresenius-medical-care': "Fresenius Medical Care has disputed characterizations of its dialysis care as prioritizing profit over patient outcomes, stating it provides high-quality care to patients who require life-sustaining treatment. Fresenius reached a $231 million DOJ settlement for FCPA violations and Medicare fraud without admitting wrongdoing, stating it has implemented comprehensive compliance reforms. No formal public response to specific allegations about its lobbying against home dialysis reimbursement parity has been documented.",
  'hsbc': "HSBC acknowledged its money laundering compliance failures in its 2012 $1.9 billion DOJ deferred prosecution agreement, stating the conduct was unacceptable and that it had fundamentally reformed its financial crime compliance function. HSBC entered a five-year monitorship and stated it had invested billions in compliance infrastructure. On its financing of fossil fuel projects following net-zero commitments, HSBC has disputed greenwashing characterizations while acknowledging ongoing reviews of its financing standards. HSBC has stated it is committed to achieving net-zero financed emissions by 2050.",
  'lyft': "Lyft has disputed characterizations of its driver classification practices as deliberately exploitative, stating that most drivers prefer the flexibility of independent contractor status. Following California's Proposition 22 — which Lyft co-funded at approximately $200 million — Lyft stated it provides meaningful benefits to app-based workers while preserving their flexibility. On safety concerns, Lyft has stated it has implemented enhanced background check and safety features. Lyft has disputed the characterization that its surge pricing model exploits users during emergencies.",
  'stellantis': "Stellantis has acknowledged emissions testing failures at Fiat Chrysler (a predecessor entity) and paid regulatory settlements. On the UAW corruption scandal involving FCA executives who paid bribes to union officials, Stellantis (as FCA's successor) has stated it has implemented enhanced ethics and compliance programs. No formal public response to specific allegations about its EV transition pace has been documented beyond general electrification commitment statements.",
  'volkswagen-group': "Volkswagen Group formally admitted to the defeat device fraud in its 2017 guilty plea, paying approximately $30 billion in global settlements. VW's CEO at the time of disclosure, Matthias Müller, stated the company was committed to full transparency and remediation. VW has stated it has undergone a fundamental transformation of its compliance and governance culture. Current CEO Oliver Blume has stated VW has drawn the appropriate consequences from the scandal. Volkswagen disputes that its leadership structure — controlled by the Piëch and Porsche families — creates accountability gaps, stating its supervisory board provides appropriate oversight.",

  // ─── v6 ───────────────────────────────────────────────────────────────────
  '3m': "3M has acknowledged PFAS contamination in communities near its manufacturing facilities and agreed to settlements totaling approximately $10.3 billion for water system contamination and $9.1 billion for defective military earplugs. 3M has stated that PFAS compounds were manufactured in good faith based on the scientific understanding at the time and that it has worked proactively to address contamination. On the Combat Arms earplug defect, 3M disputed that the earplugs were defective while simultaneously reaching the $9.1 billion settlement, stating the settlement avoids protracted litigation. 3M has stated it stopped manufacturing PFAS in 2002 and is committed to environmental remediation.",
  'diageo': "Diageo has disputed characterizations of its marketing practices as targeting vulnerable populations, stating it complies with self-regulatory advertising codes globally. Diageo has stated it invests in responsible drinking programs through its DRINKiQ platform and industry initiatives. No formal public response to specific allegations about its water usage in drought-stressed regions has been documented beyond general water stewardship commitments.",
  'glencore': "Glencore has acknowledged its FCPA and UK Bribery Act violations in its 2022 guilty plea covering bribery in Nigeria, Cameroon, Ivory Coast, Equatorial Guinea, Brazil, Venezuela, and the DRC, agreeing to pay over $1.5 billion. Glencore's CEO Gary Nagle stated the conduct was unacceptable and that the company had fundamentally reformed its compliance culture. On its Congo mining operations and documented human rights concerns, Glencore has stated it is committed to responsible mining and has implemented community development programs. Glencore has stated it terminated the executives involved in bribery.",
  'ikea': "IKEA has disputed characterizations of its tax structure as aggressive avoidance, stating its use of foundations and transfer pricing complies with applicable law and reflects legitimate commercial arrangements. On wood sourcing from endangered forests, IKEA has stated it is committed to sustainable forestry and sources wood from certified suppliers, while acknowledging that supply chain verification in complex global supply chains is an ongoing challenge. IKEA has stated it is working toward using only recycled or sustainably sourced materials by 2030.",
  'lactalis': "Lactalis has not issued comprehensive formal public responses to its contamination history beyond individual recall notices and settlements. Following the 2017 salmonella contamination affecting infants, Lactalis acknowledged the contamination and paid compensation to affected families. Lactalis has not addressed media investigations into its practice of maintaining infected product in the supply chain after the contamination was discovered. No formal public response to allegations about its corporate governance opacity has been documented. No formal public response from Lactalis to these specific pattern allegations has been documented in credible sources as of this profile's research date.",
  'medtronic': "Medtronic has disputed characterizations of its InFuse bone growth product as deliberately misrepresented to surgeons, stating it provided appropriate risk disclosures and that physician-initiated use of products outside labeling is not Medtronic's responsibility. Medtronic reached a $2.8 million settlement with the DOJ over InFuse marketing without admitting wrongdoing. On its tax inversion to Ireland through the Covidien acquisition, Medtronic has stated the transaction was commercially motivated and legally structured. No formal public response to specific allegations about its pricing practices has been documented.",
  'mondelez-international': "Mondelez International has acknowledged child labor concerns in its West African cocoa supply chain and published annual progress reports on its Cocoa Life sustainability program. Mondelez has stated it is committed to eliminating child labor from its supply chain and has invested over $400 million in cocoa sustainability programs. Mondelez has disputed characterizations of its marketing practices as deliberately targeting children, stating it complies with applicable advertising codes. No formal public response to specific FCPA allegations has been documented beyond the settlement payment.",
  'purdue-pharma': "Purdue Pharma and the Sackler family have disputed the most severe characterizations of their culpability, while the company itself pleaded guilty to federal charges in 2007 and again in 2020. The Sackler family members who served on the board have disputed that their involvement constituted knowing participation in fraud, characterizing their role as governance oversight rather than operational direction. Richard Sackler's internal communications — released through litigation — are documented primary sources rather than allegations; Purdue has stated these documents have been taken out of context. The Sackler family agreed to pay approximately $6 billion in the bankruptcy settlement without admitting personal wrongdoing.",
  'rio-tinto': "Rio Tinto has acknowledged the destruction of the Juukan Gorge Aboriginal heritage site as 'a source of great sadness' and a 'terrible mistake,' resulting in the resignations of its CEO, Chief Commercial Officer, and head of copper and iron ore divisions. Rio Tinto stated it has implemented fundamental reforms to its heritage management processes and community consultation procedures. On Bougainville Copper mine environmental damage, Rio Tinto has acknowledged historical environmental harm and has stated it is committed to working with affected communities on remediation. On its Oyu Tolgoi water rights disputes in Mongolia, Rio Tinto has stated it is working within the applicable regulatory framework.",
  'sanofi': "Sanofi has disputed characterizations of its insulin pricing practices as exploitative, stating that its net prices after rebates are significantly lower than list prices and that it provides patient assistance programs. Sanofi has acknowledged the Depakine valproate birth defect failures in France, reaching settlements with affected families and stating it has implemented enhanced pregnancy warning measures. On its Dengvaxia dengue vaccine deployment in the Philippines, Sanofi acknowledged that it had not adequately communicated risks for patients with no prior dengue infection — a disclosure that contributed to the Philippine government's withdrawal of the vaccine program. Sanofi has stated it has enhanced its clinical trial disclosure practices.",

  // ─── v7 ───────────────────────────────────────────────────────────────────
  'bridgestone': "Bridgestone has disputed characterizations of its rubber sourcing practices as knowingly dependent on forced labor, stating it conducts due diligence audits of its supply chain and requires suppliers to comply with its CSR purchasing guidelines. Following the price-fixing cartel settlement, Bridgestone acknowledged the conduct and paid its $425 million fine, stating it had implemented enhanced competition law compliance programs. No formal public response to specific allegations about its Liberian rubber plantation labor conditions has been documented beyond general sustainability statements.",
  'grupo-bimbo': "Grupo Bimbo has not issued formal public responses to specific allegations about its market dominance practices and distributor treatment beyond general statements about competitive business practices. Grupo Bimbo has stated it complies with applicable competition law in all markets. No formal public response to specific allegations about its trade practices in Mexico and Latin America has been documented in credible sources as of this profile's research date.",
  'lowes': "Lowe's has disputed characterizations of its labor practices as systematically problematic, stating it provides competitive wages and benefits. On EEOC settlements for discrimination claims, Lowe's has reached settlements without admitting wrongdoing and stated it has implemented enhanced anti-discrimination training. Lowe's has stated it is committed to environmental sustainability through its product sourcing standards. No formal public response to specific supply chain labor allegations has been documented beyond general supplier code of conduct statements.",
  'michelin': "Michelin has disputed characterizations of its natural rubber sourcing as knowingly dependent on exploitative labor practices, stating it conducts third-party audits of its supply chain and participates in the Global Platform for Sustainable Natural Rubber. Michelin has stated it is committed to responsible sourcing and has published supplier standards. No formal public response to specific allegations about its anticompetitive conduct investigations in Europe has been documented beyond general compliance statements.",
  'tsmc': "TSMC has not issued formal public responses to specific allegations about its role in the US-China technology competition beyond stating that it complies with all applicable export control regulations and cooperates with government inquiries. On environmental concerns about its water usage in Taiwan, TSMC has stated it has invested in water recycling and efficiency technology. On labor conditions at its Arizona facilities, TSMC has acknowledged cultural adaptation challenges and worker concerns, and has stated it is working with its US workforce on integration. TSMC has disputed characterizations of its Taiwan workforce as subject to mandatory overtime beyond legal requirements.",

  // ─── Additional early corporate profiles ──────────────────────────────────
  'amazon': "Amazon has disputed characterizations of its warehouse working conditions as systematically dangerous, stating it has invested billions in safety technology and ergonomics. Amazon has stated its injury rates are calculated differently from industry peers and that comparisons overstate relative risk. On unionization, Amazon has stated it respects workers' rights to organize while vigorously contesting union elections it believes were conducted improperly. Amazon disputed the FTC antitrust suit characterizations, stating its practices benefit consumers through lower prices and faster delivery. On tax avoidance, Amazon has stated it pays all taxes legally required and that its tax structure reflects legitimate business operations.",
  'apple': "Apple has disputed characterizations of its App Store practices as anticompetitive, stating the 30% commission reflects the value Apple provides and is consistent with industry standards for curated platforms. Apple has stated it investigates all allegations of labor violations in its supply chain and has published annual supplier responsibility reports. On privacy, Apple has stated its approach — including CSAM scanning proposals and App Tracking Transparency — reflects genuine commitment to user privacy. Apple has disputed Epic Games' characterization of App Store practices in litigation; courts have issued mixed rulings.",
  'meta': "Meta has disputed characterizations of its algorithmic amplification of harmful content as deliberate, stating it has invested billions in content moderation and safety infrastructure. On the Cambridge Analytica scandal, Meta acknowledged the data sharing violated its policies and paid the $5 billion FTC fine — the largest privacy settlement in FTC history — while stating the consent decree reforms address the underlying issues. On mental health impacts on teen girls, Meta disputed Frances Haugen's characterizations while simultaneously announcing teen safety features, stating it takes user wellbeing seriously.",
  'google': "Google has disputed EU antitrust findings characterizing its search and Android practices as illegal, while paying billions in fines and implementing required changes. Google has stated its search results reflect genuine algorithmic relevance rather than competitive self-preferencing. On employee pay equity settlements, Google has stated it is committed to equal pay and has implemented enhanced compensation review processes. On privacy practices, Google has disputed characterizations of its data collection as exceeding user consent, while implementing changes required by regulatory settlements globally.",
  'microsoft': "Microsoft has generally acknowledged past antitrust issues while characterizing its current practices as compliant. On the Activision Blizzard acquisition, Microsoft acknowledged labor violations at Activision Blizzard as a concern and stated it would not interfere with workers' right to organize. Microsoft has stated its AI practices through Azure OpenAI are committed to responsible AI development. No formal public response to specific allegations about its government surveillance cooperation beyond published transparency reports has been documented.",
  'tesla': "Tesla has disputed NHTSA safety investigations as reflecting misunderstandings of its Autopilot and Full Self-Driving systems, stating these are driver assistance systems that require driver attention. Following multiple recalls, Tesla has stated its over-the-air update capability allows faster safety remediation than traditional recalls. On labor practices, Tesla has disputed NLRB findings of worker intimidation, appealing rulings it characterizes as legally incorrect. Elon Musk has publicly disputed the characterization of Tesla's workplace as hostile to union organizing.",
  'exxonmobil': "ExxonMobil has disputed the characterization that its internal climate research established the reality of human-caused climate change while it publicly disputed that reality, stating its scientists' work was exploratory and that the company's public statements accurately reflected scientific uncertainty at the time. ExxonMobil has stated it supports a carbon price as a market-based climate solution. On its Valdez spill, ExxonMobil has stated it paid billions in cleanup costs and has implemented enhanced spill prevention technology. ExxonMobil has stated it is investing in lower-emission technologies.",
  'chevron': "Chevron has vigorously disputed the $9.5 billion Ecuadorian judgment for Amazon contamination as the product of fraud and corruption in the Ecuadorian legal proceedings, obtaining a US federal court ruling finding the judgment was obtained through corrupt means. Chevron has stated it did not operate the contaminated wells — Texaco did, before Chevron's acquisition — and that Texaco remediated its share of contamination before leaving Ecuador. Steven Donziger, the attorney who won the Ecuadorian judgment, was subsequently disbarred and imprisoned on contempt charges in proceedings Chevron funded.",
  'mcdonalds': "McDonald's has disputed characterizations of its franchisee wage practices as systematically exploitative, stating that franchisees are independent business owners responsible for their employment decisions. Following the NLRB joint employer rulings, McDonald's stated it is not a joint employer of franchisee workers. McDonald's has stated it has raised wages at company-owned restaurants and has implemented training programs through Hamburger University. On health impacts of its food, McDonald's has stated it provides nutritional information and has reformulated products to reduce sodium and other ingredients.",
  'pfizer': "Pfizer has disputed characterizations of its COVID-19 vaccine trial as having inadequately disclosed adverse events, stating its mRNA vaccine demonstrated safety and efficacy in the largest global vaccination program in history. On its $2.3 billion DOJ settlement for fraudulent marketing of Bextra and other drugs, Pfizer paid without admitting wrongdoing and stated it has implemented enhanced compliance programs. On insulin pricing, Pfizer has stated it provides patient assistance programs and that list prices do not reflect what most patients pay after insurance.",
  'unitedhealth': "UnitedHealth Group has disputed characterizations of its prior authorization practices as systematically designed to deny valid claims, stating its coverage decisions are made by clinicians based on medical evidence. Following the Change Healthcare cyberattack, UnitedHealth stated it has invested significantly in cybersecurity and worked to restore services quickly. On its acquisition of physician practices, UnitedHealth has stated vertical integration improves care coordination. UnitedHealth has disputed DOJ antitrust suit characterizations of its Change Healthcare acquisition.",
  'jpmorgan-chase': "JPMorgan Chase has acknowledged multiple regulatory settlements including the $13 billion mortgage securities settlement — the largest bank settlement in US history at the time — while generally not admitting wrongdoing. CEO Jamie Dimon has stated the bank has implemented comprehensive reforms and that the conduct in most settlements predates the current management culture. On the Jeffrey Epstein banking relationship, JPMorgan settled for $290 million and stated it should have exited the relationship earlier. JPMorgan has stated it has implemented enhanced financial crime compliance.",
  'bank-of-america': "Bank of America has acknowledged multiple regulatory settlements including the $16.65 billion mortgage securities settlement without admitting wrongdoing in most cases, stating these resolved legacy issues from the Countrywide and Merrill Lynch acquisitions. Bank of America has stated it has implemented comprehensive compliance reforms and that its current business practices are fundamentally different from those at issue in the settlements.",
  'goldman-sachs': "Goldman Sachs has acknowledged its role in the 1MDB scandal through its $2.9 billion global settlement — the largest in the bank's history — admitting that its former bankers paid bribes to secure bond business. CEO David Solomon stated the conduct was unacceptable and that Goldman had implemented fundamental compliance reforms. Goldman has stated its current culture is categorically different from the era of the ABACUS CDO fraud, for which it paid a $550 million SEC settlement. Goldman has disputed characterizations of its Treasury Department revolving door as inherently corrupt, stating government service and private sector experience are complementary.",
  'wells-fargo': "Wells Fargo acknowledged the fraudulent account scandal as a fundamental failure of its culture and leadership, resulting in multiple CEO departures and a Federal Reserve asset cap that remains in place. Wells Fargo paid $3 billion in DOJ and SEC settlements for the fake account scandal. Former CEO John Stumpf paid a $17.5 million personal fine and was banned from banking. Current CEO Charlie Scharf has stated Wells Fargo has undergone fundamental transformation of its risk and control infrastructure. Wells Fargo has stated it has remediated customers harmed by the fake account scandal.",
  'cigna': "Cigna has disputed characterizations of its prior authorization denial practices as systematically designed to avoid paying valid claims, stating its medical directors review claims individually. Following the ProPublica investigation documenting automated mass denials, Cigna stated it has reformed its review process. On its PBM practices, Cigna has disputed characterizations of its Express Scripts subsidiary's spread pricing as patient harm, stating its integrated model reduces costs. No formal public response to specific allegations about its premium pricing practices has been documented beyond general healthcare affordability statements.",
  'unitedhealth': "UnitedHealth has disputed characterizations of its prior authorization and claim denial practices as systematically designed to limit care, stating its coverage decisions follow clinical guidelines. No formal public response to the Luigi Mangione case context has been documented.",
  'mckesson': "McKesson has disputed characterizations of its opioid distribution practices as knowingly facilitating illegal diversion, stating it distributed legally manufactured pharmaceuticals through licensed channels and that addressing diversion is law enforcement's responsibility. McKesson reached an $8.9 billion opioid settlement without admitting wrongdoing and has stated it has implemented enhanced suspicious order monitoring systems. McKesson has stated that pharmaceutical distributors are not responsible for manufacturer marketing practices.",
  'eli-lilly': "Eli Lilly has disputed characterizations of its insulin pricing as unjustified, stating its net prices after rebates are significantly lower than list prices and that it provides significant patient assistance. Following sustained public pressure, Eli Lilly announced a cap of $35/month on out-of-pocket insulin costs for commercially insured patients in 2023 — an acknowledgment that previous pricing created access barriers. Eli Lilly has stated it invests heavily in research that generates medical advances justifying its revenue levels.",
  'merck': "Merck has disputed characterizations of its Vioxx withdrawal as delayed beyond when safety evidence required action, stating it withdrew the product promptly when a clinical trial showed unambiguous cardiovascular risk. Merck paid approximately $4.85 billion in Vioxx settlements without admitting wrongdoing. On its HPV vaccine Gardasil, Merck has disputed adverse event characterizations as involving its vaccine rather than coincidental conditions. No formal public response to specific allegations about its drug pricing practices has been documented beyond general statements about the value of pharmaceutical innovation.",
  'bayer-monsanto': "Bayer has acknowledged glyphosate litigation risk following its acquisition of Monsanto, reaching a $10.9 billion settlement covering approximately 125,000 Roundup cancer claims without admitting that glyphosate causes cancer. Bayer has stated it stands behind the safety of glyphosate when used as directed and that the scientific consensus, including EPA's position, supports glyphosate's safety. Bayer has stated it is developing new herbicide alternatives. On Monsanto's PCB contamination legacy, Bayer has stated it is addressing cleanup obligations as Monsanto's successor.",
};

// ─── Response detection ────────────────────────────────────────────────────
const RESPONSE_MARKERS = [
  'has publicly disputed',
  'has formally disputed',
  'has disputed',
  'has acknowledged',
  'has stated it has',
  'has not issued',
  'has not retracted',
  'has not formally responded',
  'no formal public response',
  'no documented public response',
  'no public response',
  'stated it has implemented',
  'paying without admitting',
  'paid without admitting',
  'settled without admitting',
];

function hasResponseStatement(summary) {
  const lower = summary.toLowerCase();
  return RESPONSE_MARKERS.some(m => lower.includes(m));
}

function defaultResponse(brandName) {
  return `No formal public response from ${brandName} to these specific allegations has been documented in credible sources as of this profile's research date.`;
}

// ─── Main ──────────────────────────────────────────────────────────────────
let patched = 0;
let skipped = 0;
let errors = 0;

const batches = [
  'profiles_v3','profiles_v4','profiles_v5','profiles_v6','profiles_v7',
  'profiles_v8','profiles_v9','profiles_v10','profiles_v11','profiles_v12',
  'profiles_v13','profiles_v14','profiles_v15'
];

for (const batch of batches) {
  const batchDir = join(__dirname, batch);
  if (!existsSync(batchDir)) continue;

  const files = readdirSync(batchDir).filter(f => f.endsWith('.json'));
  for (const file of files) {
    const filePath = join(batchDir, file);
    try {
      const profile = JSON.parse(readFileSync(filePath, 'utf8'));
      const slug = profile.brand_slug || file.replace('.json', '');
      const brandName = profile.brand_name || slug;

      if (!profile.allegations || !profile.allegations.summary) {
        skipped++;
        continue;
      }

      const current = profile.allegations.summary;

      // Check if it already has a real response (not just the Type 3 default)
      const hasDefault = current.includes('No formal public response from');
      const hasReal = hasResponseStatement(current) && !hasDefault;

      if (hasReal) {
        // Already has a substantive response — skip
        skipped++;
        continue;
      }

      const knownResponse = KNOWN_RESPONSES[slug];
      if (!knownResponse) {
        // No known response and already has Type 3 default — leave it
        skipped++;
        continue;
      }

      // Strip the Type 3 default if present, then append the known response
      let base = current;
      if (hasDefault) {
        const defaultIdx = base.indexOf('No formal public response from');
        if (defaultIdx > 0) {
          base = base.substring(0, defaultIdx).trimEnd();
        }
      }

      profile.allegations.summary = base + ` ${knownResponse}`;

      writeFileSync(filePath, JSON.stringify(profile, null, 2));
      console.log(`  ✓ ${slug}`);
      patched++;

    } catch (err) {
      console.error(`  ✗ Error on ${file}: ${err.message}`);
      errors++;
    }
  }
}

console.log(`\nDone. Upgraded: ${patched} | Already adequate: ${skipped} | Errors: ${errors}`);
console.log('\nNext: node db/import_all_profiles.mjs to push to DB');
